### PR TITLE
bandaid for #75, conservatively propagate `AllEscape` upon pointer operations

### PR DESCRIPTION
**Pull request by aviatesk**
As well as for unhandled `:foreigncall`s.

### CODE REVIEW

**Comment by vtjnash** [comment]
Neither pointer nor most ccall are an escape.

**Comment by aviatesk** [comment]
Don't we need to escape the operands of pointer operations and ccall?

**Comment by vtjnash** [comment]
No, since the GC releases it, the analysis can also release it

**Comment by aviatesk** [comment]
So here is my understanding:

Pointer operations literately work on pointers, and so they don't escape their operands (as obviously `Ptr` is just `bitstype` itself).
If we don't do some pointer analysis, it would be (mostly) enough if impose escape at pointer construction sites.
So for example, if we impose `AllEscape` when seeing `:jl_value_ptr` ccall, we can safely ignore escapes via `pointerref`.
I still think we need to account for escapes via certain "setter" pointer operations, e.g. we need to impose additional escape on operands of `pointerset` in order to handle this kind of case correctly:
```julia
julia> result = code_escapes((String,)) do s
           ref  = Ref("foo")
           ref1 = Ref(ref)
           ref2 = Ref(s)
           GC.@preserve ref2 begin
               ptr  = pointer_from_objref(ref1)
               ptr′ = Ptr{Any}(ptr)
               unsafe_store!(ptr′, ref2)
               return unsafe_load(ptr′) # should escape s and ref1
           end
       end
#27(_2::String *) in Main at none:2
2 X  1 ─ %1 = %new(Base.RefValue{String}, "foo")::Base.RefValue{String}                              │╻╷╷ Ref
3 X  │   %2 = %new(Base.RefValue{Base.RefValue{String}}, %1)::Base.RefValue{Base.RefValue{String}}   │╻╷╷ Ref
4 ↓  │   %3 = %new(Base.RefValue{String}, _2)::Base.RefValue{String}                                 │╻╷╷ Ref
5 ◌  │        $(Expr(:gc_preserve_begin, :(%3)))                                                     │   
6 ◌  │   %5 = $(Expr(:foreigncall, :(:jl_value_ptr), Ptr{Nothing}, svec(Any), 0, :(:ccall), :(%2)))::Ptr{Nothing}_from_objref
7 ◌  │   %6 = Core.bitcast(Ptr{Any}, %5)::Ptr{Any}                                                   │╻   Ptr
8 ◌  │        Base.pointerset(%6, %3, 1, 1)::Ptr{Any}                                                │╻╷  unsafe_store!
9 ↑  │   %8 = Base.pointerref(%6, 1, 1)::Any                                                         │╻╷  unsafe_load
  ◌  └──      return %8                                                                                                                                      │   
```

---

As for ccalls, I think I don't understand what you mean by "the GC releases it".
I think some ccalls can take `jl_value_t` for example, and do whatever things they want (like invoking `jl_apply_generic` for example). And I'm not sure how GC can release its argument. Since it is implicit to convert a valid Julia object to the pointer when such ccalls are called, we should conservatively escape their arguments?
For analysis correctness, I also think we need to account for the possibility that return value of some ccall can sometimes be aliased to any of their argument.

**Pull request closed without merging**
